# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aa3aff0a0b6e1840b18358b3a89879ee573843575af52756be10ff9eb9f1bff453aeeced590b61aa94f45f1bbb8da8912a90aeb4122cb36b7af54b1d1af1ad2

test:
  secret_key_base: a763cf460b78d8390c9176710ccbd2f3d3be239151352048e1e00b616b6e433f33840a70be5eb6974d1923ec39ae5febb2e28dcc8a10b5fc442a576caf86d17b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
